### PR TITLE
[WIP] Individual pages example.

### PR DESCRIPTION
**Pull request by benubois**
This is a crazy idea to address #9.

The result is a copy of `index.html` is created for every photo in `photos`, but with the proper Open Graph metadata. The result is interesting. 

I think the biggest downside of this approach is the increased build time.

When using the `DSCXXXXX.jpg` style image names, the resulting urls were not very pretty. However, what if the images were given titles that were used to generate the permalink and `<title>`?

Here's what that looks like in the URL bar and tab title:

Screen Shot 2020-03-07 at 8 29 53 PM

Screen Shot 2020-03-07 at 8 29 56 PM

Screen Shot 2020-03-07 at 8 29 59 PM

### CODE REVIEW

**Comment by benubois** [comment]
Here's what the card looks like for [https://5e63f7095b97930008f0daee--maxvoltar-photo.netlify.com/tough-duck/#tough-duck.jpg](https://5e63f7095b97930008f0daee--maxvoltar-photo.netlify.com/tough-duck/#tough-duck.jpg)

Screen Shot 2020-03-07 at 8 39 36 PM

**Comment by maxvoltar** [comment]
Can we do this without the `#photo.jpg` part of the URL?

I like the idea of giving photos custom names. We could turn `A sunny day on the beach.jpg` to `/a-sunny-day-on-the-beach` for URL's and `A sunny day on the beach` for page titles, RSS...

**Comment by benubois** [comment]
Yeah! It would mean losing your nice `:target` based approach to making photos full screen, but it’s certainly doable.

**Comment by maxvoltar** [comment]
The loading behavior would be pretty much the same, right? `tint` and `thumbnail` are already loaded in the browser, so they'll appear instantly and `large` will load in afterwards giving that nice blurry-to-sharp effect. 

Would there be a page load in between or is it all smoke and mirrors?

**Comment by benubois** [comment]
> The loading behavior would be pretty much the same, right?

Yes, I think it could be made to feel the same.

> Would there be a page load in between or is it all smoke and mirrors?

No, JavaScript is hijacking link clicks. The page URL still changes using `replaceState`, so copying and pasting the URL will always take you to the right place.

I'll update it so we can take a look at the result.

**Pull request closed without merging**
